[options]
admin_passwd = $pbkdf2-sha512$600000$Z8z5vzdmDGFsrXVurZWScg$IlcQ5mvQQtcLRGWldsi25rXpu.Bv2D8ssTrjBUMASvffXJ6VnG7owzJ49veebXPBEIyWN/sb4QlWAB3XjB75Xg
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
data_dir = /var/lib/odoo
http_interface = 0.0.0.0
http_port = 8069
log_level = info

